### ISSUE TITLE
The example doesn't work

### ISSUE THREAD

**Issue by deviant-logic** [ekmett/hyperloglog#1]
`size (foldr insert mempty [1..10] :: HyperLogLog $(4))`
`>>> Approximate {_confidence = 0.9972, _lo = 0, _estimate = 0, _hi = 0}`

**Comment by ekmett** [comment]
This has been fixed. 

We use a better hash function in 0.3 and 0.3.1 also lets you specify your own hash function.

**Comment by ozataman** [comment]
@ekmett Thank you for implementing insertHash!

**Comment by ekmett** [comment]
Sorry that took so long. It was embarrassingly easy.

**Comment by ozataman** [comment]
Indeed! If anything, it is more embarrassing that I didn't just send you a PR!

**Comment by mdeland** [comment]
Awesome!
