### ISSUE TITLE
provide a Serial instance

### ISSUE THREAD

**Issue by cartazio** [ekmett/hyperloglog#11]
currently HyperLogLog only provides a Cereal Serialize, and it'd be super handy to also provide a Serial instance. That *may* have the knock on effect of pushing bytes to provide a Data.Vector instance for Serial perhaps?

**Comment by ekmett** [comment]
I suppose I should just incur the `bytes` dependency and get both.

**Comment by ekmett** [comment]
Worse, I already have the dependencies, just not the instances.

**Comment by ekmett** [comment]
Closed by 95f8824637973d5c965f4832ff0 and ab124334b71449e93
