### ISSUE TITLE
No valid build plain avalable for latest version

### ISSUE THREAD

**Issue by arianvp** [ekmett/hyperloglog#23]
I and @kosmikus have been researching this during Munihac, but we cannot get a valid build plain (Exhaustive search) on the current version of hyperloglog.

We can get it to use by removing the upper bounds for the following projects:

```
cabal new-build  --allow-newer="binary,comonad,pointed"
```

**Comment by Drezil** [comment]
seems to be done with https://github.com/ekmett/hyperloglog/commit/e11f1701f135be32d77fc51ec33c64841ce8c296 - but that update got not pushed to hackage..

**Comment by RyanGlScott** [comment]
Fixed in [`hyperloglog-0.4.1`](http://hackage.haskell.org/package/hyperloglog-0.4.1).
