### ISSUE TITLE
Incompatible with lens > 4.4

### ISSUE THREAD

**Issue by MichaelXavier** [ekmett/hyperloglog#6]
Hi,

In Config.hs you specify the option createInstance when deriving lenses for the config. This option went away in 4.4 and causes a build failure in any lens versions beyond that.
https://github.com/ekmett/hyperloglog/blob/master/src/Data/HyperLogLog/Config.hs#L91

I think the solution is just to remove createInstance. I'll submit a PR to that effect but obviously you'd know better than me if that's the right approach.

**Comment by glguy** [comment]
This issue is resolved in the currently released version
